name: Branch Push CI Workflow
run-name: ${{ github.actor }} testing and building the frontend
on:
  push:
    branches-ignore:
      - "main"
jobs:
  npm-install-test-build:
    name: "npm install, test, and build"
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - name: List job info
        run: |
          echo "Running on ${{ runner.os }} server hosted by github"
          echo "Job was triggered by ${{ github.event_name }}"
          echo "Branch name is ${{ github.ref }}"
      - name: Checkout the repository code
        uses: actions/checkout@v4.2.0
      - run: echo "Repo name is ${{ github.repository }} is cloned to the runner"
      - run: echo "Ready to test code on the runner"
      - name: List files in the repo
        run: |
          ls ${{ github.workspace }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.x"
          cache: "npm"
      - name: Check Node.js and npm versions
        run: |
          node -v
          npm -v
      - name: NPM install
        run: npm install
      - name: NPM Test
        run: npm test
      - name: NPM Build
        run: npm run build
      - name: List files in the ws after commands
        run: |
          ls ${{ github.workspace }}
